image_width: 1920
image_height: 1080
camera_name: orbbec_gemini_330
distortion_model: rational_polynomial
camera_matrix:
  rows: 3
  cols: 3
  dt: d
  data:
  - 1037.4278564453125
  - 0.0
  - 961.91845703125
  - 0.0
  - 1037.8446044921875
  - 535.6334838867188
  - 0.0
  - 0.0
  - 1.0
distortion_coefficients:
  rows: 1
  cols: 8
  dt: d
  data:
  - 0.006196156144142151
  - -0.04576879367232323
  - 0.00020464631961658597
  - -0.0006971054244786501
  - 0.031182406470179558
  - 0.0
  - 0.0
  - 0.0
rectification_matrix:
  rows: 3
  cols: 3
  dt: d
  data:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
projection_matrix:
  rows: 3
  cols: 4
  dt: d
  data:
  - 1037.4278564453125
  - 0.0
  - 961.91845703125
  - 0.0
  - 0.0
  - 1037.8446044921875
  - 535.6334838867188
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0